import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import NavBar from "@/components/navBar/NavBar";
import Footer from "@/components/footer/Footer";
// import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import CartProvider from "@/context/CartContext";
import WishlistProvider from "@/context/WishlistContext";
import AuthProvider from "@/context/AuthContext";
import InternetChecker from "@/components/common/InternetChecker";
import ReactQueryProvider from "@/context/ReactQueryContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "E-shop | Home",
    template: "E-shop | %s ",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <ReactQueryProvider>
          <AuthProvider>
            <WishlistProvider>
            <CartProvider>
              <NavBar />
              <Toaster
                position="bottom-center"
                toastOptions={{
                  duration: 5000,
                  className: "text-xl sm:text-2xl font-semibold",
                }}
              />
              {children}
              <Footer />
            </CartProvider>
            </WishlistProvider>
          </AuthProvider>
          <InternetChecker />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
